name: ai_chatbot_nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.5.1
      - sentence-transformers==2.6.1
      - tensorflow==2.15.0
      - keras==2.15.0
      - tf-keras
      - flask==3.0.3
